# Generated by Django 4.2.25 on 2025-10-26 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('day_number', models.PositiveSmallIntegerField(verbose_name='Номер дня (1–7)')),
                ('reward_amount', models.PositiveIntegerField(default=0, verbose_name='Награда (монеты)')),
            ],
            options={
                'verbose_name': 'Ежедневная награда',
                'verbose_name_plural': 'Ежедневные награды',
                'db_table': 'ежедневные_награды',
            },
        ),
        migrations.CreateModel(
            name='DailyRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения')),
            ],
            options={
                'verbose_name': 'Полученная награда',
                'verbose_name_plural': 'Полученные награды',
                'db_table': 'полученные_награды',
            },
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название сбоя')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Сбой',
                'verbose_name_plural': 'Сбои',
                'db_table': 'сбои',
            },
        ),
        migrations.CreateModel(
            name='RuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('rule_text', models.TextField(verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Правило по категории',
                'verbose_name_plural': 'Правила по категориям',
                'db_table': 'правила_по_категориям',
            },
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Время (сек)')),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('failure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='game.failure', verbose_name='Сбой')),
            ],
            options={
                'verbose_name': 'Очки',
                'verbose_name_plural': 'Очки',
                'db_table': 'очки',
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
            ],
            options={
                'verbose_name': 'Выполнение задания',
                'verbose_name_plural': 'Выполнения заданий',
                'db_table': 'выполнения_заданий',
            },
        ),
        migrations.DeleteModel(
            name='Gift',
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='task',
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='simulationconfig',
            options={'verbose_name': 'Симуляция', 'verbose_name_plural': 'Симуляции'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='round_number',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='total_rounds',
        ),
        migrations.RemoveField(
            model_name='simulationconfig',
            name='cost',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text',
            field=models.TextField(default=1, verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='attempt_cost',
            field=models.PositiveIntegerField(default=200, verbose_name='Цена за попытку'),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='reward_level_1',
            field=models.PositiveIntegerField(default=100, verbose_name='Награда 1 уровня'),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='reward_level_2',
            field=models.PositiveIntegerField(default=500, verbose_name='Награда 2 уровня'),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='reward_level_3',
            field=models.PositiveIntegerField(default=1000, verbose_name='Награда 3 уровня'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='answers',
            field=models.JSONField(default=list, verbose_name='Список ответов'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Правильный ответ (индекс)'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.URLField(blank=True, verbose_name='Иконка (URL)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.PositiveIntegerField(default=0, verbose_name='Награда (монеты)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс монет'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterModelTable(
            name='quizquestion',
            table='вопросы',
        ),
        migrations.AlterModelTable(
            name='simulationconfig',
            table='симуляции',
        ),
        migrations.AlterModelTable(
            name='task',
            table='задания',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='профили_пользователей',
        ),
        migrations.DeleteModel(
            name='LeaderboardEntry',
        ),
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='game.userprofile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='game.task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='scoreentry',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='game.userprofile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='dailyrewardclaim',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to='game.userprofile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='dailyrewardclaim',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='game.dailyreward', verbose_name='Награда'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together={('profile', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyrewardclaim',
            unique_together={('profile', 'reward')},
        ),
    ]
