# Generated by Django 4.2.26 on 2025-11-08 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import game.models  # используем generate_referral_code


def fill_referral_codes(apps, schema_editor):
    UserProfile = apps.get_model("game", "UserProfile")

    # Соберём уже занятые значения (если вдруг были)
    used = set(
        UserProfile.objects.exclude(referral_code__isnull=True)
                           .exclude(referral_code="")
                           .values_list("referral_code", flat=True)
    )

    # Для всех пустых — сгенерируем уникальные коды
    for p in UserProfile.objects.all():
        if p.referral_code:
            continue
        for _ in range(50):  # перестраховка от коллизий
            code = game.models.generate_referral_code()
            if code and code not in used:
                used.add(code)
                p.referral_code = code
                p.save(update_fields=["referral_code"])
                break
        else:
            raise RuntimeError("Cannot generate unique referral_code for profile id=%s" % p.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_adsgram_assignment"),
    ]

    operations = [
        # ---- 1) Поле link к Task (безопасно)
        migrations.AddField(
            model_name="task",
            name="link",
            field=models.URLField(blank=True, verbose_name="Ссылка (URL)"),
        ),

        # ---- 2) referral_code: добавляем как nullable, без unique и без default
        migrations.AddField(
            model_name="userprofile",
            name="referral_code",
            field=models.CharField(
                max_length=12,
                null=True,
                blank=True,
                editable=False,
                verbose_name="Реферальный код",
            ),
        ),

        # ---- 3) referred_by
        migrations.AddField(
            model_name="userprofile",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="game.userprofile",
                verbose_name="Пригласивший пользователь",
            ),
        ),

        # ---- 4) Модель QuizAttempt (как было)
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "mode",
                    models.CharField(
                        default="quiz", max_length=32, verbose_name="Режим"
                    ),
                ),
                (
                    "correct_answers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество правильных ответов"
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего вопросов"
                    ),
                ),
                (
                    "reward",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Полученная награда"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата завершения",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="game.userprofile",
                        verbose_name="Профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка викторины",
                "verbose_name_plural": "Попытки викторины",
                "db_table": "попытки_викторины",
            },
        ),

        # ---- 5) Заполняем referral_code уникальными значениями
        migrations.RunPython(fill_referral_codes, migrations.RunPython.noop),

        # ---- 6) Ужесточаем ограничения: теперь unique + not null
        migrations.AlterField(
            model_name="userprofile",
            name="referral_code",
            field=models.CharField(
                max_length=12,
                unique=True,
                null=False,
                blank=False,
                editable=False,
                verbose_name="Реферальный код",
            ),
        ),
    ]
