# Generated by Django 4.2.26 on 2025-11-08 11:58

from __future__ import annotations

import secrets
import string

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

TABLE_NAME = '"профили_пользователей"'

ADD_REFERRAL_CODE_SQL = f"""
ALTER TABLE {TABLE_NAME}
ADD COLUMN IF NOT EXISTS referral_code varchar(12);
"""

ADD_REFERRED_BY_SQL = f"""
ALTER TABLE {TABLE_NAME}
ADD COLUMN IF NOT EXISTS referred_by_id bigint;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'профили_пользователей'
          AND column_name = 'referred_by_id'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'userprofile_referred_by_id_fk'
    ) THEN
        ALTER TABLE {TABLE_NAME}
        ADD CONSTRAINT userprofile_referred_by_id_fk
        FOREIGN KEY (referred_by_id)
        REFERENCES {TABLE_NAME}(id)
        ON DELETE SET NULL;
    END IF;
END $$;
"""

DROP_REFERRAL_CODE_RELATION_SQL = f"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relname = 'профили_пользователей_referral_code_c3c85ba'
    ) THEN
        DROP INDEX IF EXISTS "профили_пользователей_referral_code_c3c85ba";
    END IF;
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'профили_пользователей_referral_code_c3c85ba'
    ) THEN
        ALTER TABLE {TABLE_NAME}
        DROP CONSTRAINT IF EXISTS "профили_пользователей_referral_code_c3c85ba";
    END IF;
END $$;
"""

SET_REFERRAL_CODE_NOT_NULL_SQL = f"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'профили_пользователей'
          AND column_name = 'referral_code'
    ) THEN
        ALTER TABLE {TABLE_NAME}
        ALTER COLUMN referral_code SET NOT NULL;
    END IF;
END $$;
"""

CREATE_REFERRAL_CODE_UNIQUE_SQL = f"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'профили_пользователей'
          AND column_name = 'referral_code'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY (c.conkey)
        WHERE c.contype = 'u'
          AND t.relname = 'профили_пользователей'
          AND a.attname = 'referral_code'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = current_schema()
          AND tablename = 'профили_пользователей'
          AND indexdef ILIKE '%UNIQUE%'
          AND indexdef ILIKE '%(referral_code)%'
    ) THEN
        CREATE UNIQUE INDEX IF NOT EXISTS userprofile_referral_code_uniq
        ON {TABLE_NAME}(referral_code)
        WHERE referral_code IS NOT NULL;
    END IF;
END $$;
"""


def _table_has_column(cursor, column_name: str) -> bool:
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'профили_пользователей'
          AND column_name = %s
        LIMIT 1;
        """,
        [column_name],
    )
    return cursor.fetchone() is not None


def _generate_code(length: int = 12) -> str:
    alphabet = string.ascii_uppercase + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def fill_referral_codes(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if not _table_has_column(cursor, "referral_code"):
            return

        cursor.execute(
            f"""
            SELECT referral_code
            FROM {TABLE_NAME}
            WHERE referral_code IS NOT NULL AND referral_code <> '';
            """
        )
        used_codes = {row[0] for row in cursor.fetchall() if row[0]}

        cursor.execute(
            f"""
            SELECT id
            FROM {TABLE_NAME}
            WHERE referral_code IS NULL OR referral_code = ''
            ORDER BY id;
            """
        )
        rows = cursor.fetchall()

        for (profile_id,) in rows:
            for _ in range(100):
                code = _generate_code()
                if code in used_codes:
                    continue
                used_codes.add(code)
                cursor.execute(
                    f"""
                    UPDATE {TABLE_NAME}
                    SET referral_code = %s
                    WHERE id = %s;
                    """,
                    [code, profile_id],
                )
                break
            else:
                raise RuntimeError(
                    f"Cannot generate unique referral_code for profile id={profile_id}"
                )


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_adsgram_assignment"),
    ]

    operations = [
        # ---- 1) Поле link к Task (безопасно)
        migrations.AddField(
            model_name="task",
            name="link",
            field=models.URLField(blank=True, verbose_name="Ссылка (URL)"),
        ),

        # ---- 2) referral_code: добавляем как nullable, без unique и без default
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(ADD_REFERRAL_CODE_SQL, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="userprofile",
                    name="referral_code",
                    field=models.CharField(
                        max_length=12,
                        null=True,
                        blank=True,
                        editable=False,
                        verbose_name="Реферальный код",
                    ),
                ),
            ],
        ),

        # ---- 3) referred_by
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(ADD_REFERRED_BY_SQL, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="userprofile",
                    name="referred_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="game.userprofile",
                        verbose_name="Пригласивший пользователь",
                    ),
                ),
            ],
        ),

        # ---- 4) Модель QuizAttempt (как было)
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "mode",
                    models.CharField(
                        default="quiz", max_length=32, verbose_name="Режим"
                    ),
                ),
                (
                    "correct_answers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество правильных ответов"
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего вопросов"
                    ),
                ),
                (
                    "reward",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Полученная награда"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата завершения",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="game.userprofile",
                        verbose_name="Профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка викторины",
                "verbose_name_plural": "Попытки викторины",
                "db_table": "попытки_викторины",
            },
        ),

        # ---- 5) Заполняем referral_code уникальными значениями
        migrations.RunPython(fill_referral_codes, migrations.RunPython.noop),

        # ---- 6) Ужесточаем ограничения: теперь unique + not null
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    DROP_REFERRAL_CODE_RELATION_SQL, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    SET_REFERRAL_CODE_NOT_NULL_SQL, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    CREATE_REFERRAL_CODE_UNIQUE_SQL, reverse_sql=migrations.RunSQL.noop
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="userprofile",
                    name="referral_code",
                    field=models.CharField(
                        max_length=12,
                        unique=True,
                        null=False,
                        blank=False,
                        editable=False,
                        verbose_name="Реферальный код",
                    ),
                ),
            ],
        ),
    ]
