# Generated by Django 4.2.26 on 2025-11-08 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_task_link_userprofile_referral_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Промокод"
                    ),
                ),
                (
                    "reward",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество монет",
                    ),
                ),
                (
                    "max_redemptions",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимум активаций",
                    ),
                ),
                (
                    "redemptions_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество активаций"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
                "db_table": "промокоды",
            },
        ),
        migrations.CreateModel(
            name="PromoCodeRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата активации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Активация промокода",
                "verbose_name_plural": "Активации промокодов",
                "db_table": "активации_промокодов",
            },
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="reward",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Награда за правильный ответ",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="referral_code",
            field=models.CharField(
                default=game.models.generate_referral_code,
                editable=False,
                max_length=12,
                unique=True,
                verbose_name="Реферальный код",
            ),
        ),
        migrations.AddConstraint(
            model_name="scoreentry",
            constraint=models.UniqueConstraint(
                fields=("profile", "failure"), name="uniq_score_per_failure"
            ),
        ),
        migrations.AddField(
            model_name="promocoderedemption",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promo_redemptions",
                to="game.userprofile",
                verbose_name="Профиль",
            ),
        ),
        migrations.AddField(
            model_name="promocoderedemption",
            name="promo_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redemptions",
                to="game.promocode",
                verbose_name="Промокод",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promocoderedemption",
            unique_together={("promo_code", "profile")},
        ),
    ]
