# Generated by Django 4.2.26 on 2025-11-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_promocode_promocoderedemption_quizquestion_reward_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationconfig",
            name="duration_seconds",
            field=models.PositiveSmallIntegerField(
                default=60, verbose_name="Длительность тренировки (сек)"
            ),
        ),
    ]
