# Generated by Django 4.2.26 on 2025-11-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_simulationconfig_duration_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="failure",
            name="bombs_max_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Максимум бомб за игру"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="bombs_min_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Минимум бомб за игру"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="bonus_price_freeze",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Цена бонуса заморозка"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="bonus_price_no_bombs",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Цена бонуса отключение бомб"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="bonus_price_x10",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Цена бонуса x10"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="bonus_price_x2",
            field=models.PositiveIntegerField(default=0, verbose_name="Цена бонуса x2"),
        ),
        migrations.AddField(
            model_name="failure",
            name="bonus_price_x5",
            field=models.PositiveIntegerField(default=0, verbose_name="Цена бонуса x5"),
        ),
        migrations.AddField(
            model_name="failure",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                default=60, verbose_name="Длительность попытки (сек)"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="max_bonuses_per_run",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="Максимум бонусов за игру"
            ),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="reward_amount_1",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Размер награды 1"
            ),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="reward_amount_2",
            field=models.PositiveIntegerField(
                default=150, verbose_name="Размер награды 2"
            ),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="reward_amount_3",
            field=models.PositiveIntegerField(
                default=250, verbose_name="Размер награды 3"
            ),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="reward_threshold_1",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Порог капель для награды 1"
            ),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="reward_threshold_2",
            field=models.PositiveIntegerField(
                default=200, verbose_name="Порог капель для награды 2"
            ),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="reward_threshold_3",
            field=models.PositiveIntegerField(
                default=300, verbose_name="Порог капель для награды 3"
            ),
        ),
        migrations.CreateModel(
            name="SimulationRewardClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("threshold", models.PositiveIntegerField(verbose_name="Порог капель")),
                ("claimed_for_date", models.DateField(verbose_name="Дата начисления")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_reward_claims",
                        to="game.userprofile",
                        verbose_name="Профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Награда симуляции",
                "verbose_name_plural": "Награды симуляции",
                "db_table": "simulation_reward_claims",
                "unique_together": {("profile", "threshold", "claimed_for_date")},
            },
        ),
        migrations.CreateModel(
            name="FailureBonusPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("x2", "x2"),
                            ("x5", "x5"),
                            ("x10", "x10"),
                            ("freeze", "freeze"),
                            ("no_bombs", "no_bombs"),
                        ],
                        max_length=32,
                        verbose_name="Тип бонуса",
                    ),
                ),
                (
                    "failure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_purchases",
                        to="game.failure",
                        verbose_name="Сбой",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_bonus_purchases",
                        to="game.userprofile",
                        verbose_name="Профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупка бонуса сбоя",
                "verbose_name_plural": "Покупки бонусов сбоя",
                "db_table": "покупки_бонусов_сбоя",
                "unique_together": {("profile", "failure", "bonus_type")},
            },
        ),
    ]
