# Generated by Django 4.2.26 on 2025-11-09 09:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_failure_bombs_max_count_failure_bombs_min_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisementButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Подпись кнопки"),
                ),
                ("link", models.URLField(verbose_name="Ссылка")),
                ("image", models.URLField(verbose_name="Изображение (URL)")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекламная кнопка",
                "verbose_name_plural": "Рекламные кнопки",
                "db_table": "рекламные_кнопки",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="FrontendConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(
                        default="default",
                        max_length=50,
                        unique=True,
                        verbose_name="Идентификатор конфигурации",
                    ),
                ),
                (
                    "screen_texture",
                    models.URLField(blank=True, verbose_name="Текстура экрана (URL)"),
                ),
            ],
            options={
                "verbose_name": "Настройки фронтенда",
                "verbose_name_plural": "Настройки фронтенда",
                "db_table": "настройки_фронтенда",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dailyrewardclaim",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dailyrewardclaim",
            name="claimed_for_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Дата награды"
            ),
        ),
        migrations.AddField(
            model_name="dailyrewardclaim",
            name="sequence_day",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ],
                verbose_name="День последовательности",
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="main_prize_image",
            field=models.URLField(
                blank=True, verbose_name="Изображение главного приза (URL)"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="main_prize_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Название главного приза"
            ),
        ),
        migrations.AddField(
            model_name="rulecategory",
            name="icon",
            field=models.URLField(blank=True, verbose_name="Иконка (URL)"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_reward_last_claimed_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последней ежедневной награды"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_reward_streak",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(8),
                ],
                verbose_name="Серия ежедневных наград",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreward",
            name="day_number",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ],
                verbose_name="Номер дня (1–8)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="icon",
            field=models.URLField(blank=True, verbose_name="Изображение (URL)"),
        ),
        migrations.AddConstraint(
            model_name="dailyrewardclaim",
            constraint=models.UniqueConstraint(
                fields=("profile", "claimed_for_date"),
                name="unique_daily_reward_claim_per_day",
            ),
        ),
    ]
