# Generated by Django 4.2.26 on 2025-11-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_advertisementbutton_frontendconfig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralProgramConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "reward_for_activation",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Награда за активацию реферального кода"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки реферальной программы",
                "verbose_name_plural": "Настройки реферальной программы",
                "db_table": "реферальные_настройки",
            },
        ),
        migrations.AddField(
            model_name="advertisementbutton",
            name="reward_amount",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Награда за переход (монеты)"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="attempt_cost",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Стоимость попытки (монеты)"
            ),
        ),
        migrations.CreateModel(
            name="AdvertisementButtonRewardClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата начисления"
                    ),
                ),
                (
                    "button",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_claims",
                        to="game.advertisementbutton",
                        verbose_name="Рекламная кнопка",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advert_reward_claims",
                        to="game.userprofile",
                        verbose_name="Профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Начисление за рекламу",
                "verbose_name_plural": "Начисления за рекламу",
                "db_table": "начисления_рекламных_переходов",
                "unique_together": {("button", "profile")},
            },
        ),
    ]
