# Generated by Django 4.2.26 on 2025-11-08 12:15

from __future__ import annotations

import secrets
import string

from django.db import migrations

TABLE_NAME = '"профили_пользователей"'

ADD_REFERRAL_CODE_SQL = f'''
ALTER TABLE {TABLE_NAME}
ADD COLUMN IF NOT EXISTS referral_code varchar(12);
'''

ADD_REFERRED_BY_SQL = f'''
ALTER TABLE {TABLE_NAME}
ADD COLUMN IF NOT EXISTS referred_by_id bigint;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'профили_пользователей'
          AND column_name = 'referred_by_id'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'userprofile_referred_by_id_fk'
    ) THEN
        ALTER TABLE {TABLE_NAME}
        ADD CONSTRAINT userprofile_referred_by_id_fk
        FOREIGN KEY (referred_by_id)
        REFERENCES {TABLE_NAME}(id)
        ON DELETE SET NULL;
    END IF;
END $$;
'''

SET_REFERRAL_CODE_NOT_NULL_SQL = f'''
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'профили_пользователей'
          AND column_name = 'referral_code'
    ) THEN
        ALTER TABLE {TABLE_NAME}
        ALTER COLUMN referral_code SET NOT NULL;
    END IF;
END $$;
'''

CREATE_REFERRAL_CODE_UNIQUE_SQL = f'''
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'профили_пользователей'
          AND column_name = 'referral_code'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY (c.conkey)
        WHERE c.contype = 'u'
          AND t.relname = 'профили_пользователей'
          AND a.attname = 'referral_code'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = current_schema()
          AND tablename = 'профили_пользователей'
          AND indexdef ILIKE '%UNIQUE%'
          AND indexdef ILIKE '%(referral_code)%'
    ) THEN
        CREATE UNIQUE INDEX IF NOT EXISTS userprofile_referral_code_uniq
        ON {TABLE_NAME}(referral_code)
        WHERE referral_code IS NOT NULL;
    END IF;
END $$;
'''


def _table_has_column(cursor, column_name: str) -> bool:
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'профили_пользователей'
          AND column_name = %s
        LIMIT 1;
        """,
        [column_name],
    )
    return cursor.fetchone() is not None


def _generate_code(length: int = 12) -> str:
    alphabet = string.ascii_uppercase + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def fill_referral_codes(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if not _table_has_column(cursor, "referral_code"):
            return

        cursor.execute(
            f"""
            SELECT referral_code
            FROM {TABLE_NAME}
            WHERE referral_code IS NOT NULL AND referral_code <> '';
            """
        )
        used_codes = {row[0] for row in cursor.fetchall() if row[0]}

        cursor.execute(
            f"""
            SELECT id
            FROM {TABLE_NAME}
            WHERE referral_code IS NULL OR referral_code = ''
            ORDER BY id;
            """
        )
        rows = cursor.fetchall()

        for (profile_id,) in rows:
            for _ in range(100):
                code = _generate_code()
                if code in used_codes:
                    continue
                used_codes.add(code)
                cursor.execute(
                    f"""
                    UPDATE {TABLE_NAME}
                    SET referral_code = %s
                    WHERE id = %s;
                    """,
                    [code, profile_id],
                )
                break
            else:
                raise RuntimeError(
                    f"Cannot generate unique referral_code for profile id={profile_id}"
                )


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_failure_shop_enabled"),
    ]

    operations = [
        migrations.RunSQL(ADD_REFERRAL_CODE_SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(ADD_REFERRED_BY_SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.RunPython(fill_referral_codes, migrations.RunPython.noop),
        migrations.RunSQL(
            SET_REFERRAL_CODE_NOT_NULL_SQL, reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            CREATE_REFERRAL_CODE_UNIQUE_SQL, reverse_sql=migrations.RunSQL.noop
        ),
    ]
