# Generated by Django 4.2.26 on 2025-11-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_fix_userprofile_referral_code_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo_url",
            field=models.URLField(
                blank=True,
                default="",
                verbose_name="Ссылка на аватар Telegram",
            ),
        ),
    ]
